logging:
  level:
    root: INFO

spring:
  sleuth:
    sampler:
      probability: 1.0
  kafka:
    bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  zipkin:
    sender:
      type: kafka
  application:
    name: elastic-query-web-client
  profiles:
    active: elastic_query_web
  config:
    import: 'configserver:'
  cloud:
    config:
      name: elastic-query-web-client,config-client
      username: spring_cloud_user
      password: '1234'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: elastic-query-web-client