spring:
  application:
    name: kafka-streams-service
  profiles:
    active: kafka_streams
  config:
    import: 'configserver:'
  cloud:
    config:
      name: kafka-streams-service,config-client
      username: spring_cloud_user
      password: '1234'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: kafka-streams-service